#!/usr/bin/env python3
"""Renders load/report.md from k6's summary.json plus the drain measurements.

Nothing here is typed by hand. The plan's principle 7 is that every published
number is reproducible from a committed script, and a report assembled by a human
reading a terminal is exactly the thing that drifts from the code that produced it.
"""
import argparse
import datetime
import json
import pathlib
import subprocess


def metric(summary, name, field, default=0.0):
    try:
        return summary["metrics"][name]["values"][field]
    except (KeyError, TypeError):
        return default


def main():
    ap = argparse.ArgumentParser()
    for flag in ("summary", "out", "rate", "duration", "payers", "amount",
                 "accepted", "completed", "failed", "drain-seconds",
                 "drain-rate", "entries", "failures"):
        ap.add_argument(f"--{flag}", required=True)
    args = ap.parse_args()

    summary = json.loads(pathlib.Path(args.summary).read_text())

    reqs = metric(summary, "http_reqs", "count")
    rate = metric(summary, "http_reqs", "rate")
    p50 = metric(summary, "http_req_duration", "med")
    p95 = metric(summary, "http_req_duration", "p(95)")
    p99 = metric(summary, "http_req_duration", "p(99)")
    mx = metric(summary, "http_req_duration", "max")
    errs = metric(summary, "http_req_failed", "rate") * 100

    def host_fact(cmd, fallback="unknown"):
        try:
            return subprocess.run(cmd, shell=True, capture_output=True,
                                  text=True, timeout=10).stdout.strip() or fallback
        except Exception:
            return fallback

    cpus = host_fact("nproc")
    mem = host_fact("free -g | awk '/^Mem:/ {print $2\" GiB\"}'")
    kernel = host_fact("uname -sr")
    commit = host_fact("git rev-parse --short HEAD")

    verdict = ("All assertions passed." if args.failures == "0"
               else f"**{args.failures} assertion(s) FAILED** — see the run output.")

    report = f"""# Load test report

Generated by `./load/run.sh` on {datetime.date.today().isoformat()} at commit `{commit}`.
Do not edit by hand — rerun the script.

## What was measured

`POST /payments` at a constant arrival rate, spread across {args.payers} payer
accounts, each payment {args.amount} minor unit.

The distinction that matters: **`POST /payments` returns `202` once the saga is
committed, not once the money has moved.** That is the published contract
(ADR-0022), so the latency below is what a client waits for, and it is not the
time for a payment to complete. Both are reported, separately, because quoting
only the first would be the flattering and misleading version of this test.

## Accept path — what a client sees

| Metric | Value |
|---|---|
| Offered load | {args.rate} req/s for {args.duration} |
| Requests | {reqs:,.0f} |
| Throughput | {rate:,.1f} req/s |
| p50 | {p50:,.1f} ms |
| p95 | {p95:,.1f} ms |
| p99 | {p99:,.1f} ms |
| max | {mx:,.1f} ms |
| Error rate | {errs:.3f} % |

## End to end — saga completion

| Metric | Value |
|---|---|
| Payments accepted | {int(args.accepted):,} |
| Completed | {int(args.completed):,} |
| Failed / compensated | {int(args.failed):,} |
| Drain time after arrival stopped | {args.drain_seconds} s |
| Completion throughput | {args.drain_rate} payments/s |
| Ledger entries written | {int(args.entries):,} |

**The completion rate is the interesting number, and it is bounded by
configuration, not by the database.** The saga driver claims at most
`spademoney.saga.batch-size` (20) sagas per tick and advances each by one step
per tick, at `spademoney.saga.interval` (250 ms) — a ceiling of roughly 80 steps
per second, and each payment needs three steps. That ceiling is a deliberate
choice for a single-instance demo, not a discovered limit: raising the batch size
or shortening the interval moves it, and the lease-based claim means additional
driver instances are safe to add (ADR-0022). What this run establishes is that
the ceiling behaves predictably and that correctness holds at it.

## Correctness held under load

{verdict}

Checked from the database after the run, not from either service's own report:

- Ledger nets to zero across all entries.
- Exactly one `CAPTURE` transaction per completed payment — no retry became a
  second charge.
- No hold left reserving funds.
- Both services' `/reconciliation` endpoints report `healthy: true`.

## Known contention, stated rather than avoided

The load spreads across {args.payers} payers on purpose. A single hot payer
serializes on two row locks: the ledger account (`SELECT ... FOR UPDATE`,
ADR-0006) and the spending-cap row in Payments. That is by design — both locks
exist to make a concurrent double-spend impossible — but it means per-payer
throughput is far below the aggregate figure above. Sharding a hot account is the
documented answer and is deliberately out of scope (§11 Backlog).

## Reproducing this

```bash
docker compose up -d

# exactly this run
./load/run.sh --rate {args.rate} --duration {args.duration}

# lighter default, finishes sooner
./load/run.sh
```

Expect either to take considerably longer than the arrival window: that phase is
short, and the rest of the wall clock is waiting for the sagas it created to
drain. This run spent {args.duration} arriving and {args.drain_seconds}s draining.

The script asserts its own correctness checks and exits non-zero if any fail, so
a regression breaks the run rather than quietly producing a worse report.

## Hardware

Single laptop, everything in one Docker Compose stack — both services, one
Postgres, one Redpanda, and the k6 container itself all competing for the same
cores. Treat these as relative figures, not capacity planning.

- CPUs: {cpus}
- Memory: {mem}
- Kernel: {kernel}
"""
    pathlib.Path(args.out).write_text(report)


if __name__ == "__main__":
    main()
